export type BibleBook = {
  short: string;
  full: string;
  number: number;
};

export const BIBLE_BOOKS: BibleBook[] = [
  { short: '창', full: '창세기', number: 1 },
  { short: '출', full: '출애굽기', number: 2 },
  { short: '레', full: '레위기', number: 3 },
  { short: '민', full: '민수기', number: 4 },
  { short: '신', full: '신명기', number: 5 },
  { short: '수', full: '여호수아', number: 6 },
  { short: '삿', full: '사사기', number: 7 },
  { short: '룻', full: '룻기', number: 8 },
  { short: '삼상', full: '사무엘상', number: 9 },
  { short: '삼하', full: '사무엘하', number: 10 },
  { short: '왕상', full: '열왕기상', number: 11 },
  { short: '왕하', full: '열왕기하', number: 12 },
  { short: '대상', full: '역대상', number: 13 },
  { short: '대하', full: '역대하', number: 14 },
  { short: '스', full: '에스라', number: 15 },
  { short: '느', full: '느헤미야', number: 16 },
  { short: '에', full: '에스더', number: 17 },
  { short: '욥', full: '욥기', number: 18 },
  { short: '시', full: '시편', number: 19 },
  { short: '잠', full: '잠언', number: 20 },
  { short: '전', full: '전도서', number: 21 },
  { short: '아', full: '아가', number: 22 },
  { short: '사', full: '이사야', number: 23 },
  { short: '렘', full: '예레미야', number: 24 },
  { short: '애', full: '예레미야애가', number: 25 },
  { short: '겔', full: '에스겔', number: 26 },
  { short: '단', full: '다니엘', number: 27 },
  { short: '호', full: '호세아', number: 28 },
  { short: '욜', full: '요엘', number: 29 },
  { short: '암', full: '아모스', number: 30 },
  { short: '옵', full: '오바댜', number: 31 },
  { short: '욘', full: '요나', number: 32 },
  { short: '미', full: '미가', number: 33 },
  { short: '나', full: '나훔', number: 34 },
  { short: '합', full: '하박국', number: 35 },
  { short: '습', full: '스바냐', number: 36 },
  { short: '학', full: '학개', number: 37 },
  { short: '슥', full: '스가랴', number: 38 },
  { short: '말', full: '말라기', number: 39 },

  { short: '마', full: '마태복음', number: 40 },
  { short: '막', full: '마가복음', number: 41 },
  { short: '눅', full: '누가복음', number: 42 },
  { short: '요', full: '요한복음', number: 43 },
  { short: '행', full: '사도행전', number: 44 },
  { short: '롬', full: '로마서', number: 45 },
  { short: '고전', full: '고린도전서', number: 46 },
  { short: '고후', full: '고린도후서', number: 47 },
  { short: '갈', full: '갈라디아서', number: 48 },
  { short: '엡', full: '에베소서', number: 49 },
  { short: '빌', full: '빌립보서', number: 50 },
  { short: '골', full: '골로새서', number: 51 },
  { short: '살전', full: '데살로니가전서', number: 52 },
  { short: '살후', full: '데살로니가후서', number: 53 },
  { short: '딤전', full: '디모데전서', number: 54 },
  { short: '딤후', full: '디모데후서', number: 55 },
  { short: '딛', full: '디도서', number: 56 },
  { short: '몬', full: '빌레몬서', number: 57 },
  { short: '히', full: '히브리서', number: 58 },
  { short: '약', full: '야고보서', number: 59 },
  { short: '벧전', full: '베드로전서', number: 60 },
  { short: '벧후', full: '베드로후서', number: 61 },
  { short: '요일', full: '요한일서', number: 62 },
  { short: '요이', full: '요한이서', number: 63 },
  { short: '요삼', full: '요한삼서', number: 64 },
  { short: '유', full: '유다서', number: 65 },
  { short: '계', full: '요한계시록', number: 66 },
];
