export type BibleBook = {
  short: string;
  full: string;
  engShort: string;
  engFull: string;
  number: number;
};

export const BIBLE_BOOKS: BibleBook[] = [
  { short: '창', full: '창세기', engShort: 'Gen', engFull: 'Genesis', number: 1 },
  { short: '출', full: '출애굽기', engShort: 'Ex', engFull: 'Exodus', number: 2 },
  { short: '레', full: '레위기', engShort: 'Lev', engFull: 'Leviticus', number: 3 },
  { short: '민', full: '민수기', engShort: 'Num', engFull: 'Numbers', number: 4 },
  { short: '신', full: '신명기', engShort: 'Deut', engFull: 'Deuteronomy', number: 5 },
  { short: '수', full: '여호수아', engShort: 'Josh', engFull: 'Joshua', number: 6 },
  { short: '삿', full: '사사기', engShort: 'Jg', engFull: 'Judges', number: 7 },
  { short: '룻', full: '룻기', engShort: 'Ru', engFull: 'Ruth', number: 8 },
  { short: '삼상', full: '사무엘상', engShort: '1Sam', engFull: '1Samuel', number: 9 },
  { short: '삼하', full: '사무엘하', engShort: '2Sam', engFull: '2Samuel', number: 10 },
  { short: '왕상', full: '열왕기상', engShort: '1Ki', engFull: '1Kings', number: 11 },
  { short: '왕하', full: '열왕기하', engShort: '2Ki', engFull: '2Kings', number: 12 },
  { short: '대상', full: '역대상', engShort: '1Chr', engFull: '1Chronicles', number: 13 },
  { short: '대하', full: '역대하', engShort: '2Chr', engFull: '2Chronicles', number: 14 },
  { short: '스', full: '에스라', engShort: 'Ezra', engFull: 'Ezra', number: 15 },
  { short: '느', full: '느헤미야', engShort: 'Neh', engFull: 'Nehemiah', number: 16 },
  { short: '에', full: '에스더', engShort: 'Est', engFull: 'Esther', number: 17 },
  { short: '욥', full: '욥기', engShort: 'Job', engFull: 'Job', number: 18 },
  { short: '시', full: '시편', engShort: 'Ps', engFull: 'Psalms', number: 19 },
  { short: '잠', full: '잠언', engShort: 'Pr', engFull: 'Proverbs', number: 20 },
  { short: '전', full: '전도서', engShort: 'Ec', engFull: 'Ecclesiastes', number: 21 },
  { short: '아', full: '아가', engShort: 'Song', engFull: 'Song of Solomon', number: 22 },
  { short: '사', full: '이사야', engShort: 'Is', engFull: 'Isaiah', number: 23 },
  { short: '렘', full: '예레미야', engShort: 'Jer', engFull: 'Jeremiah', number: 24 },
  { short: '애', full: '예레미야애가', engShort: 'Lam', engFull: 'Lamentations', number: 25 },
  { short: '겔', full: '에스겔', engShort: 'Ezek', engFull: 'Ezekiel', number: 26 },
  { short: '단', full: '다니엘', engShort: 'Dan', engFull: 'Daniel', number: 27 },
  { short: '호', full: '호세아', engShort: 'Hos', engFull: 'Hosea', number: 28 },
  { short: '욜', full: '요엘', engShort: 'Joel', engFull: 'Joel', number: 29 },
  { short: '암', full: '아모스', engShort: 'Am', engFull: 'Amos', number: 30 },
  { short: '옵', full: '오바댜', engShort: 'Obad', engFull: 'Obadiah', number: 31 },
  { short: '욘', full: '요나', engShort: 'Jonah', engFull: 'Jonah', number: 32 },
  { short: '미', full: '미가', engShort: 'Mic', engFull: 'Micah', number: 33 },
  { short: '나', full: '나훔', engShort: 'Nah', engFull: 'Nahum', number: 34 },
  { short: '합', full: '하박국', engShort: 'Hab', engFull: 'Habakkuk', number: 35 },
  { short: '습', full: '스바냐', engShort: 'Zeph', engFull: 'Zephaniah', number: 36 },
  { short: '학', full: '학개', engShort: 'Hag', engFull: 'Haggai', number: 37 },
  { short: '슥', full: '스가랴', engShort: 'Zech', engFull: 'Zechariah', number: 38 },
  { short: '말', full: '말라기', engShort: 'Mal', engFull: 'Malachi', number: 39 },
  { short: '마', full: '마태복음', engShort: 'Mt', engFull: 'Matthew', number: 40 },
  { short: '막', full: '마가복음', engShort: 'Mk', engFull: 'Mark', number: 41 },
  { short: '눅', full: '누가복음', engShort: 'Lk', engFull: 'Luke', number: 42 },
  { short: '요', full: '요한복음', engShort: 'Jn', engFull: 'John', number: 43 },
  { short: '행', full: '사도행전', engShort: 'Acts', engFull: 'Acts', number: 44 },
  { short: '롬', full: '로마서', engShort: 'Rom', engFull: 'Romans', number: 45 },
  { short: '고전', full: '고린도전서', engShort: '1Cor', engFull: '1Corinthians', number: 46 },
  { short: '고후', full: '고린도후서', engShort: '2Cor', engFull: '2Corinthians', number: 47 },
  { short: '갈', full: '갈라디아서', engShort: 'Gal', engFull: 'Galatians', number: 48 },
  { short: '엡', full: '에베소서', engShort: 'Eph', engFull: 'Ephesians', number: 49 },
  { short: '빌', full: '빌립보서', engShort: 'Php', engFull: 'Philippians', number: 50 },
  { short: '골', full: '골로새서', engShort: 'Col', engFull: 'Colossians', number: 51 },
  {
    short: '살전',
    full: '데살로니가전서',
    engShort: '1Th',
    engFull: '1Thessalonians',
    number: 52,
  },
  {
    short: '살후',
    full: '데살로니가후서',
    engShort: '2Th',
    engFull: '2 Thessalonians',
    number: 53,
  },
  { short: '딤전', full: '디모데전서', engShort: '1Tim', engFull: '1Timothy', number: 54 },
  { short: '딤후', full: '디모데후서', engShort: '2Tim', engFull: '2 Timothy', number: 55 },
  { short: '딛', full: '디도서', engShort: 'Tit', engFull: 'Titus', number: 56 },
  { short: '몬', full: '빌레몬서', engShort: 'Phlm', engFull: 'Philemon', number: 57 },
  { short: '히', full: '히브리서', engShort: 'Heb', engFull: 'Hebrews', number: 58 },
  { short: '약', full: '야고보서', engShort: 'Jas', engFull: 'James', number: 59 },
  { short: '벧전', full: '베드로전서', engShort: '1Pet', engFull: '1Peter', number: 60 },
  { short: '벧후', full: '베드로후서', engShort: '2Pet', engFull: '2 Peter', number: 61 },
  { short: '요일', full: '요한일서', engShort: '1Jn', engFull: '1John', number: 62 },
  { short: '요이', full: '요한이서', engShort: '2Jn', engFull: '2 John', number: 63 },
  { short: '요삼', full: '요한삼서', engShort: '3Jn', engFull: '3 John', number: 64 },
  { short: '유', full: '유다서', engShort: 'Jude', engFull: 'Jude', number: 65 },
  { short: '계', full: '요한계시록', engShort: 'Rev', engFull: 'Revelation', number: 66 },
];
